TextWidget:

<TextWidget>:
    BoxLayout:
        orientation: 'vertical'
        size: root.size
        
#        Label: # comment
#            text: "Hello world.1"
#            color: 1,0,1,1 #rgba

        Label:
            text: "Drag & Drop csv-file to this window!"
            color: 0,0,0,1
            canvas.before:
                Color:
                    rgba: 0,1,1,1
                Rectangle:
                    pos: self.pos
                    size: self.size

#        Label:
#            text: root.text
#            color: 1,1,0,1


#        Button:
#            id: button1
#            text: "Click to hogehoge"
#            font_size: 30
#            on_press: root.buttonClicked()
