TextWidget:

<TextWidget>:
#<Display>
    BoxLayout:
        orientation: 'vertical'
        size: root.size
        
#        Label: # comment
#            text: "Hello world.1"
#            color: 1,0,1,1 #rgba

        Label:
            id: la01
            text: "Drag & Drop csv-file to this window!"
            color: 0,0,0,1
            canvas.before:
                Color:
                    rgba: 0,1,1,1
                Rectangle:
                    pos: self.pos
                    size: self.size

        BoxLayout:
            orientation: 'horizontal'
            size_hint_y: 0.2

            CheckBox:
                id: g0
                group: "grp1"
                active: True
                on_press: root._on_clicked()

            Label:
                text: "Line"

            CheckBox:
                id: g1
                group: "grp1"
                on_press: root._on_clicked()


            Label:
                text: "o / x"

            CheckBox:
                id: g2
                group: "grp1"
                on_press: root._on_clicked()

            Label:
                text: "point"

        BoxLayout:
            orientation: 'horizontal'
            size_hint_y: 0.2
            
            CheckBox:
                id: g3
                on_press: root._on_clicked()

            Label:
                text: "Invert X-Axis"

            CheckBox:
                id: g4
                active: True
                on_press: root._on_clicked()
            Label:
                text: "Invert Y-Axis"

#        Label:
#            text: root.text
#            color: 1,1,0,1

#        Button:
#            id: button1
#            text: "Click to hogehoge"
#            font_size: 30
#            on_press: root.buttonClicked()